services:
  hello_app:
    image: objectworld/docker-hello:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 600M
      restart_policy:
        condition: on-failure
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
    networks:
      - hello_net
 
  hello_proxy:
    image: dockercloud/haproxy
    depends_on:
      - hello_app
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 28080:80
    networks:
      - hello_net
    deploy:
      placement:
        constraints: [node.role == manager]
 
networks:
  hello_net:
    driver: overlay